#!/usr/bin/env python3

import math
import sys
from collections import defaultdict,namedtuple

import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np


State = namedtuple('State', ['positions', 'p_uuids', 'outputs', 'unknown'])


def calc_distance(t, n1, n2, state):
    ps = []

    for n in (n1,n2):
        twaypoint,x,y,z,vx,vy,vz = state.positions[n]
        dt = t - twaypoint
        ps.append((x + vx*dt, y+vy*dt, z+vz*t))

    (x1,y1,z1),(x2,y2,z2) = ps

    return  math.sqrt((x1 - x2)**2 + (y1 - y2)**2 + (z1 - z2)**2)


def unknown_event(toks, state):
    event = toks[0]
    state.unknown[event] += 1


def handle_pos(toks, state):
    t = float(toks[1])
    node_num = int(toks[2].split('/')[2])

    x,y,z,vx,vy,vz = tuple(map(float, toks[3:]))
    state.positions[node_num] = (t,x,y,z,vx,vy,vz)


def handle_phytxbegin(toks, state):
    t = float(toks[1])
    node_num = int(toks[2].split('/')[2])

    #tag       ,t      ,path                                                          ,uuid,txpower
    #phytxbegin,9.08305,/NodeList/0/DeviceList/0/$ns3::WifiNetDevice/Phys/0/PhyTxBegin,19,0.005623413252
    uid = int(toks[3])
    state.p_uuids[uid] = node_num


def handle_phyrxdrop(toks, state):
    t = float(toks[1])
    node_num = int(toks[2].split('/')[2])

    #tag       ,t         ,path                                                          ,uuid,reason
    #phyrxdrop,10.02505448,/NodeList/0/DeviceList/0/$ns3::WifiNetDevice/Phys/0/PhyRxDrop,20,PREAMBLE_DETECT_FAILURE
    if not toks[4] == 'PREAMBLE_DETECT_FAILURE':
        return

    t_msec = int(t*100) / 100
    uid = int(toks[3])
    tx_node = state.p_uuids[uid]
    d = calc_distance(t_msec, node_num, tx_node, state)

    state.outputs[(t_msec,0)] = (t_msec, 'drop', min(state.outputs.get((t_msec,0), (t_msec, 'drop', 5000.0))[-1], d))


def handle_phyrxend(toks, state):
    t = float(toks[1])
    node_num = int(toks[2].split('/')[2])

    #tag     ,t          ,path                                                        ,uuid
    #phyrxend,9.028304433,/NodeList/0/DeviceList/0/$ns3::WifiNetDevice/Phys/0/PhyRxEnd,18

    t_msec = int(t*100) / 100
    uid = int(toks[3])
    tx_node = state.p_uuids[uid]
    d = calc_distance(t_msec, node_num, tx_node, state)
    state.outputs[(t_msec,1)] = (t_msec, 'receive', max(state.outputs.get((t_msec,1), (t_msec, 'receive', -1.0))[-1], d))


if not len(sys.argv) > 1:
    print("usage: rexp-plot-min-rx-distance NS3LOGFILE", file=sys.stderr)
    exit(1)

logfile = sys.argv[1]

handle = defaultdict(lambda: unknown_event)

handle['pos'] = handle_pos
handle['phytxbegin'] = handle_phytxbegin
handle['phyrxdrop'] = handle_phyrxdrop
handle['phyrxend'] = handle_phyrxend

state = State(positions={}, p_uuids={}, outputs={}, unknown=defaultdict(lambda: 0))

for line in open(logfile):
    toks = line.strip().split(',')

    #print(toks)

    event = toks[0]

    if len(toks) < 3:
        continue

    handle[event](toks, state)

plt.style.use('ggplot')

df = pd.DataFrame(sorted(state.outputs.values()), columns=['t','packet_status','d'])

print(df.describe())

max_rx_dist = df.loc[df.packet_status == "receive"].d.max()
print(f'maximum receive distance: {max_rx_dist}')

min_drop_dist = df.loc[df.packet_status == "drop"].d.min()
print(f'minimum drop distance: {min_drop_dist}')

# Source - https://stackoverflow.com/a/3900167
# Posted by Herman Schaaf, modified by community. See post 'Timeline' for change history
# Retrieved 2026-03-19, License - CC BY-SA 4.0

matplotlib.rc('font', **{'size'   : 18})

fig = plt.figure(figsize=(12,12))

ax = fig.add_subplot()

sns.pointplot(x='t', y='d', hue='packet_status', data=df, ax=ax, palette=('#eba834', '#3480eb'))

xticks = np.arange(0, df.t.count(), 100)
xlabels = [str(xt) for xt in xticks]
ax.set_xticks(xticks, labels=xlabels)
ax.set_xlabel('packet index')
ax.set_ylabel('distance (meters)')
ax.text(80, min_drop_dist+5, f'{min_drop_dist:0.1f}')
plt.hlines(y=[min_drop_dist], xmin=0, xmax=df.t.count(), colors=['black'], linestyles=['--'])

fig.savefig(f'rx-pass-fail-by-distance.png')
