#!/usr/bin/env python3

import argparse
import os
import sys

from routeexplore.logsparser import LogsParser


if __name__=='__main__':
    parser = argparse.ArgumentParser(description='Convert trace log into multiple txt files')

    parser.add_argument('--timestep',
                        type=int,
                        default=100000000,
                        help='timestep for accumulating and outputting route state in nanoseconds. ' \
                        'default is 0.1 second (100000000 nanoseconds)')
    parser.add_argument('logdir',
                        metavar='LOGDIR',
                        help='the directory containing ns-3 .log files for parsing. The base file name ' \
                        'of each log file is taken to be the tag name by which the data is identified')
    parser.add_argument('outdir',
                        metavar='OUTPUTDIR',
                        help='root output directory for files.')

    args = parser.parse_args()

    if not os.path.isdir(args.logdir):
        print(f'bad logdir {args.logdir}, quiting')
        exit(1)

    tags ={
        f.split('.')[0]:f for f in os.listdir(args.logdir)
        if os.path.isfile(os.path.join(args.logdir, f))
    }
    print(tags)

    for tag,logfile in tags.items():
        tagdir = os.path.join(args.outdir, tag)

        os.makedirs(tagdir)

        parser = LogsParser(tagdir)

        parser.parse(os.path.join(args.logdir,logfile), args.timestep)
